<a href="https://colab.research.google.com/github/RafQuin/ELR0ND/blob/master/vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
X=np.array([[2,7,0,1,3,4],
            [1,5,3,-1,2,0]])
#vector columna de unos (6x1)
unos=np.ones((6,1))
#numero de columnas
n=X.shape[1]
# calculo de la media
med=(1/n)*np.dot(X,unos)
print("vector de medias:\n",np.round(med,2))

#calculamos el producto escalar
# med1
med1=np.mean(X[0])
# med2
med2=np.mean(X[1])
res1=X[0]-med1
res2=X[1]-med2
proe=np.dot(res1,res2)
print("producto escalar:",np.round(proe,2))
#modulo1
nor1=np.sqrt(np.sum(res1**2))
#modulo2
nor2=np.sqrt(np.sum(res2**2))
#segunda alternativa
norr1=np.linalg.norm(res1)
norr2=np.linalg.norm(res2)
print("modulo 1:",np.round(nor1,2))
print("modulo 2:",np.round(nor2,2))
print("modulo 1:",np.round(norr1,2))
print("modulo 2:",np.round(norr2,2))
cos=proe/(nor1*nor2)
print("cos(\u03b8):",np.round(cos,2))

vector de medias:
 [[2.83]
 [1.67]]
producto escalar: 13.67
modulo 1: 5.55
modulo 2: 4.83
modulo 1: 5.55
modulo 2: 4.83
cos(θ): 0.51


haciendo la prueba si va todo lo trabajado a github

In [ ]:
import numpy as np
print("hola mundo")

hola mundo


In [ ]:
import numpy as np
a=np.array([[-1,-1,-1],
            [0,1,0],
            [0,0,1]])
i=np.dot(a,a)
print("la matriz A es involutiva si\n ",i)

la matriz A es involutiva si
  [[1 0 0]
 [0 1 0]
 [0 0 1]]
